project:
  type: website
  output-dir: docs
website:
  title: "統計学の勉強ノート"
  site-url: https://nobukuni-hyakutake.github.io/statistics/
  favicon: images/math.png
  description: "A sample blog"
  google-analytics: "G-7CEVE5761Z"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Nobukuni-Hyakutake/statistics
      - icon: rss
        href: index.xml
  page-footer:
    center: 
      - text: "CC by 4.0 Nobukuni Hyakutake"
format:
  html:
    theme: cerulean
    css: styles.css
    toc: true


