project:
  type: website
  output-dir: docs
website:
  title: "統計学の勉強ノート"
  site-url: https://nobukuni-hyakutake.github.io/statistics/
  favicon: images/math.png
  description: "A sample blog"
  google-analytics: "G-7CEVE5761Z"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Nobukuni-Hyakutake/statistics
      - icon: rss
        href: index.xml
  page-footer:
    center: 
      - text: "© 2023 NO PORTION OF THIS SITE MAY BE USED FOR TRAINING A MACHINELEARNING MODEL (INCLUDING LLMS) WITHOUT THE EXPRESS WRITTENCONSENT OF THE AUTHOR."
format:
  html:
    theme: cerulean
    css: styles.css
    toc: true
    toc-title: 目次
    toc-location: body
    number-sections: true
    code-copy: true
    code-tools: true
execute:
  warning: false
