project:
  type: website
  output-dir: docs
website:
  title: "blog"
  favicon: images/math.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Nobukuni-Hyakutake/statistics
format:
  html:
    theme: cosmo
    css: styles.css



